=== RafaelITB/marcas/Uf1&UF2/Pr2/e1/e1_receptes.xsd
<!--
Rafael Guiotto y Marc Guerra
14/10/24
Pr2 â€“ XSD - Receptes
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="receptes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recepta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string" />
                            <xs:element name="passos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="pas" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="dificultat" type="xs:integer" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RafaelITB/marcas/Pr2/e1/receptes.xml
<receptes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="./e1_receptes.xsd">
   <recepta dificultat="5">
       <nom>Patates amb llet</nom>
       <passos>
           <pas>Fregim patates</pas>
           <pas>Posem-hi la llet</pas>
           <pas>deixem refredar</pas>
       </passos>
   </recepta>
   <recepta dificultat="8">
       <nom>beixamel</nom>
       <passos>
           <pas>ho remenem tot</pas>
           <pas>ho posem a la paella</pas>
       </passos>
   </recepta>
</receptes>
