=== RafaelITB/marcas/Pr2/e2 ProvesValidacio/e2_receptes.xsd
<!--
Rafael Guiotto y Marc Guerra
15/10/24
Pr2 – XSD - Receptes
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="receptes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recepta" maxOccurs="unbounded">  <!-- puede haber más de 1 'recepta' -->
                    <xs:complexType>
                        <xs:sequence>
                             <xs:element name="autor" minOccurs="0"> <!-- autor no es necesario -->
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom" type="xs:string" />
                                        <xs:element name="dni">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{8}[A-Za-z]"/> <!-- dni siempre es 8 numeros seguidos de 1 letra -->
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="ingredients">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingredient" maxOccurs="unbounded"> <!--Puede haber más de 1 'ingredient' -->
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="quantitat">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="valor" type="xs:integer" />
                                                                <xs:element name="mesura" type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="nom" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="passos"> 
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="pas" type="xs:string" maxOccurs="unbounded"/> <!-- puede haber más de 1 'pas' -->
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="dificultat">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/> <!-- la dificultad no puede ser negativa -->
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="categoria"> <!-- la categoria solo puede ser primer/segon/postres/altres -->
                            <xs:simpleType>
                                <xs:restriction base="xs:string"> 
                                    <xs:enumeration value="primer"/>
                                    <xs:enumeration value="segon"/>
                                    <xs:enumeration value="postres"/>
                                    <xs:enumeration value="altres"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RafaelITB/marcas/Uf1&UF2/Pr2/e2 ProvesValidacio/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Exemple invalid: el dni no tÃ© un format correcte  -->
<!--
        Javier Amaya Boira
        11/12/2022
        ASIXc M04 UF1 A2
        Pr2 XSD exercici 2
-->

<receptes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="e2_receptes.xsd">
    <recepta dificultat="5">
        <autor>
            <nom>John Doe</nom>
            <dni>DES2322sS</dni>
        </autor>
        <nom>Papates amb llet</nom>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>grams</mesura>
                </quantitat>
                <nom>all</nom>
            </ingredient>
        </ingredients>
        <passos>
            <pas>Fregir patates</pas>
            <pas>Posar-hi la llet</pas>
            <pas>deixar refredar</pas>
        </passos>
    </recepta>
</receptes>

=== RafaelITB/marcas/Uf1&UF2/Pr2/e2 ProvesValidacio/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--    Exemple vÃ lid  -->
<!--
        Javier Amaya Boira
        11/12/2022
        ASIXc M04 UF1 A2
        Pr2 XSD exercici 2
-->
<receptes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="e2_receptes.xsd">
    <recepta dificultat="5">
        <nom>Papates amb llet</nom>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>125</valor>
                    <mesura>grams</mesura>
                </quantitat>
                <nom>all</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>225</valor>
                    <mesura>grams</mesura>
                </quantitat>
                <nom>patata</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>1</valor>
                    <mesura>litre</mesura>
                </quantitat>
                <nom>llet</nom>
            </ingredient>
        </ingredients>
        <passos>
            <pas>Fregir patates</pas>
            <pas>Posar-hi la llet</pas>
            <pas>deixar refredar</pas>
        </passos>
    </recepta>
    <recepta dificultat="8">
        <nom>beixamel</nom>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>225</valor>
                    <mesura>grams</mesura>
                </quantitat>
                <nom>farina</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>1</valor>
                    <mesura>litre</mesura>
                </quantitat>
                <nom>llet</nom>
            </ingredient>
        </ingredients>
        <passos>
            <pas>remenar tot</pas>
            <pas>posar a la paella</pas>
        </passos>
    </recepta>
</receptes>

=== RafaelITB/marcas/Uf1&UF2/Pr2/e2 ProvesValidacio/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Exemple invalid: 'valor': 'dos' is not a valid value  -->
<!--
        Javier Amaya Boira
        11/12/2022
        ASIXc M04 UF1 A2
        Pr2 XSD exercici 2
-->
<receptes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="e2_receptes.xsd">
    <recepta dificultat="5">
        <nom>Papates amb llet</nom>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>dos</valor>
                    <mesura>grams</mesura>
                </quantitat>
                <nom>all</nom>
            </ingredient>
        </ingredients>
        <passos>
            <pas>Escalfar l'oli</pas>
            <pas>Fregir patates</pas>
        </passos>
    </recepta>
</receptes>

=== RafaelITB/marcas/Pr2/e2 ProvesValidacio/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Exemple invalid: Element 'passos': Missing child element  -->
<!--
        Javier Amaya Boira
        11/12/2022
        ASIXc M04 UF1 A2
        Pr2 XSD exercici 2
-->
<receptes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="e2_receptes.xsd">
    <recepta dificultat="5">
        <nom>Papates amb llet</nom>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>grams</mesura>
                </quantitat>
                <nom>all</nom>
            </ingredient>
        </ingredients>
        <passos>
        </passos>
    </recepta>
</receptes>

=== RafaelITB/marcas/Pr2/e2 ProvesValidacio/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Exemple invalid: 'valor': dificultat va entre 0 i 10  -->
<!--
        Javier Amaya Boira
        11/12/2022
        ASIXc M04 UF1 A2
        Pr2 XSD exercici 2
-->

<receptes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="e2_receptes.xsd">
    <recepta dificultat="100">
        <nom>Papates amb llet</nom>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>grams</mesura>
                </quantitat>
                <nom>all</nom>
            </ingredient>
        </ingredients>
        <passos>
            <pas>Fregir patates</pas>
            <pas>Posar-hi la llet</pas>
            <pas>deixar refredar</pas>
        </passos>
    </recepta>
    <recepta dificultat="-1">
        <nom>Papates amb llet2</nom>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>grams</mesura>
                </quantitat>
                <nom>all</nom>
            </ingredient>
        </ingredients>
        <passos>
            <pas>Fregir patates</pas>
            <pas>Posar-hi la llet</pas>
            <pas>Batir</pas>
            <pas>deixar refredar</pas>
        </passos>
    </recepta>
</receptes>
