=== RafaelITB/marcas/xsd/A2_xsd_ex6.1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string" />
                <xs:element name="autor" type="xs:string" />
                <xs:element name="fecha_publicacion" type="xs:date" />
                <xs:element name="hora_publicacion" type="xs:time" />
                <xs:element name="isbn" type="xs:string" />
                <xs:element name="editorial" type="xs:string" />
                <xs:element name="tapa_dura" type="xs:boolean" />
                <xs:element name="peso" type="xs:decimal" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RafaelITB/marcas/Uf1&UF2/xsd/A2_xsd_ex6.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="./A2_xsd_ex6.1.xsd">
    <titulo>Genetic Programming</titulo>
    <autor>John Koza</autor>
    <fecha_publicacion>1994-01-01</fecha_publicacion>
    <hora_publicacion>12:00:00</hora_publicacion>
    <isbn>0-202-11170-5</isbn>
    <editorial>The MIT Press</editorial>
    <tapa_dura>true</tapa_dura>
    <peso>0.5</peso>
</libro>
