=== RafaelITB/marcas/xsd/A2_xsd_ex8.1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="persona">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="mujer" type="xs:boolean" default="false" />
                <xs:element name="fecha_de_nacimiento">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dia" type="xs:integer" />
                            <xs:element name="mes" type="xs:integer" />
                            <xs:element name="anyo" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ciudad" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RafaelITB/marcas/xsd/A2_xsd_ex8.2.xml
<persona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./A2_xsd_ex8.1.xsd">
    <nombre>Maria</nombre>
    <mujer/>
    <fecha_de_nacimiento>
      <dia>21</dia>
      <mes>10</mes>
      <anyo>1998</anyo>
    </fecha_de_nacimiento>
    <ciudad>Bilbao</ciudad>
  </persona>
