=== RafaelITB/marcas/xsd/A2_xsd_ex9.1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Apellido" type="xs:string" />
                <xs:element name="Nombre" type="xs:string"/>
                <xs:element name="Empleado" type="xs:integer"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="telefono" type="xs:string"/>
                <xs:element name="direccion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="calle" type="xs:string"/>
                            <xs:element name="ciudad" type="xs:string"/>
                            <xs:element name="codigoPostal" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RafaelITB/marcas/xsd/A2_xsd_ex9.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="./A2_xsd_ex9.1.xsd">
    <Apellido>Perez</Apellido>
    <Nombre>Juan</Nombre>
    <Empleado>1234567890</Empleado>
    <email>juanperez@gmial.com</email>
    <telefono>666 555 444</telefono>
    <direccion>
        <calle>Carrer de Pau Clarisk, 121</calle>
        <ciudad>Barcelona</ciudad>
        <codigoPostal>080009</codigoPostal>
    </direccion>
</Empresa>
